### ISSUE TITLE
Vagrant installation/setup steps

### ISSUE THREAD

**Issue by wandl** [ezekg/theme-juice-cli#44]
I am not very familiar with using Vagrant do you actually need to add a default vm to it first before running theme-juice?

I keep getting the following error:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/username/base

I tried to resolve by:

1) cd to vagrant install directory and run: vagrant init hashicorp/precise32
2) run: vagrant up
3) then setup/create theme-juice project

Even though this is done do I still need to provision? https://docs.vagrantup.com/v2/getting-started/provisioning.html
 
Vagrant seems setup up but as far as I can see does not see the Customfile as the project is not synced nor is the network up?

Also theme-juice-cli seemed to create everything fine with no error I have the complete log if you want to see it?

I am very interested in getting this all worked out and having the steps very clear as I am developing a new workflow for our team members!

What am I missing here?

**Comment by ezekg** [comment]
Theme Juice will automatically install VVV inside of the `~/vagrant`, so there should be no need for installing another VM. Did you already have a VM installed in that directory? And just to make sure, you do have VirtualBox installed, correct?

Try removing `~/vagrant` and running a `tj create` from any directory. The first it should do is install and configure VVV, then create your first project.

If that doesn't work, if you wouldn't mind posting a gist of your create prompts/inputs as well as all of the output from vagrant.

**Comment by wandl** [comment]
Hi @ezekg ,

That worked thanks for all the help I really appreciate it. 

Initially when I first ran `tj create` I had a lot of permission problems with my local `.rvm` and `.npm` packages so I had to resolve that, I am guessing that the `~/vagrant` directory only got partially setup.

Deleting the vagrant installation seems to have fixed the problem as I can see a many more files have been added in the various directories.

Some suggestions:

With such an intensive setup and the vagrant step being so critical maybe adding some checks at various points to make sure certain things have happened might be good like write a .lockfile that is removed after successful setup if present means that vagrant needs a wipe.

The post provisioning scripts seem pretty hefty be good if you could pick and choose what to install in the VM. For example do not install Wordpress Stable or Dev

I also think that being able to select a linux distro would be good feature but I guess this adds a lot of complexity to things :)

I did see some errors towards the end about Grunt not being installed and phpmyadmin failed to download gist is here:
https://gist.github.com/wandl/b1ef47cf4fed2d1e859e

**Comment by ezekg** [comment]
No problem. I'm going to go ahead and close this issue up. As for the rest of your concerns, `tj` already has a pretty hefty amount of checks; you happened to just hit one of which I'm not entirely keen on doing, and that is checking whether or not the VM is 'installed' or not.

[Since it's possible to pass in any VM that follows the VVV file-structure with the `--vm-box` flag](https://github.com/ezekg/theme-juice-cli#so-does-that-mean-i-can-use-any-vagrant-box), having to keep up with what it means file-wise for a VM to be 'installed' e.g. do I check for a `Vagrantfile`, sites within `www/`, or something else? (It would actually be entirely dependent on the VM, because it could be set up oddly, and I don't want to force a certain way of doing things more than the file-structure.)

As it is now, `tj` assumes that if there is anything inside `~/vagrant` (or whatever is passed to `--vm-path`), it's a Vagrant installation that is compatible with VVV; and if there's nothing inside `~/vagrant`, then it will clone VVV into that directory and provision it. I'd prefer to keep it as simple as possible, to avoid a future maintenance headache (it can happen quickly.)

As for the default WordPress stable/dev sites, I chose not to remove those for the simple reason that I do not want to modify the VM directly. All changes made by `tj` are changes to files that are meant to be modified, and are ignored within the main VVV repository, such as the `Customfile`, `init-custom.sql`, etc. 

This ensures that at any time you can do a `git pull` to update your VVV installation without any merge conflicts. If `tj` removed those default sites, you'd get conflicts out the wazoo and be unable to fetch the latest changes without a considerable amount of work.

Lastly, you mentioned a couple issues with the provision seeming long (it definitely it!) and a some errors. Those should be filed on the [VVV-Apache](https://github.com/ericmann/vvv-apache) repo, as that is an issue with the VM box and not `tj`.  :+1:

**Comment by ezekg** [comment]
Just following up to make sure everything is going good. Let me know if you need any help. I'm going to try and record a getting started screencast soon. :+1:
