### ISSUE TITLE
Make documentation on setup command clearer

### ISSUE THREAD

**Issue by cycomarcooo** [ezekg/theme-juice-cli#60]
Hi, it seems there are some requirements to fulfil before a wp project could be migrated to theme-juice with `tj setup` like having vendor/autoload.php installed.
[Here is the full output](https://gist.github.com/cycomarcooo/00719f3a538b85f1ff91ee19a60236a3)

**Comment by ezekg** [comment]
Thanks for the issue. I agree, setting up a site that doesn't use our starter template needs to be explained better. You're getting that error because `tj` is creating a `wp-cli.local.yml` that requires Composer to run `wp` commands over SSH into your virtual machine (and sets up `wp` to use the `wp/` directory); [this comes stock with our starter template](https://github.com/ezekg/theme-juice-starter/blob/master/composer.json?ts=2#L41).

To fix this, you should use the `--no-wp-cli` flag when using `tj setup` with project's that don't use our starter template. This will skip over creating that file and avoid any errors. I think that adding a prompt during setup for this would be helping, as well as clearing it up in the docs.

This should also be the case for the `.env` file with `--modify-wp-config --no-env` flags (skips creating a `.env` file and modifies the constants in `wp-config.php` instead).

**Comment by cycomarcooo** [comment]
Thanks. Let say I'd like to create my own template (minimal). What are the minimal requirements and structure to take advantage of wp-cli, .env and all deployment features. If I understood correctly how your starter-theme works, here are the points I noticed: 
- manage plugins with Composer and here is the minimal [composer.json](https://gist.github.com/cycomarcooo/cafcc591964845c9ba78b56918a77a45)
- Juicefile (almost same as tj-starter)
- wp-cli.yml (same as tj-starter)
- app folder (same as tj-starter)

Right?

**Comment by ezekg** [comment]
Mostly correct. You don't necessarily have to have the `app/` folder; you just need WordPress installed inside of the `wp/` directory, unless you want to use the `--no-wp-cli` flag. You would also need a `wp-config.php` similar to ours which reads configuration values from a `.env` file. Everything else is optional (e.g. Grunt, Sass, Coffee, Haml, etc).

**Comment by ezekg** [comment]
Closing, as this will be resolved along with https://github.com/ezekg/theme-juice-cli/issues/69 whenever I have time to cut a new release.
